# build
FROM node:24-alpine3.22 AS builder

WORKDIR /app

COPY frontend/package.json frontend/package-lock.json ./

RUN --mount=type=cache,target=/root/.npm \
    npm ci

ARG VITE_AZURE_TENANT_ID
ARG VITE_AZURE_CLIENT_ID
ARG VITE_AZURE_API_SCOPE

ENV VITE_AZURE_TENANT_ID=$VITE_AZURE_TENANT_ID
ENV VITE_AZURE_CLIENT_ID=$VITE_AZURE_CLIENT_ID
ENV VITE_AZURE_API_SCOPE=$VITE_AZURE_API_SCOPE

COPY frontend/ .

RUN npm run build


# runtime
FROM nginx:1.31-alpine

COPY nginx/nginx.conf.template /etc/nginx/nginx.conf.template

COPY --from=builder \
    --chown=nginx:nginx \
    /app/dist \
    /usr/share/nginx/html

COPY nginx/docker-entrypoint.sh /docker-entrypoint.sh
COPY nginx/nginx.azure.conf.template /etc/nginx/templates/nginx.conf.template

RUN sed -i 's/\r$//' /docker-entrypoint.sh \
    && chmod +x /docker-entrypoint.sh \
    && mkdir -p /tmp/nginx \
    && chown -R nginx:nginx \
        /etc/nginx \
        /var/cache/nginx \
        /var/run \
        /var/log/nginx \
        /tmp/nginx

USER nginx

EXPOSE 8080

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["nginx", "-g", "daemon off;"]