# TODO: add ssl certs and https/http2/hsts once closer to prod 
worker_processes auto; 

events {
  worker_connections 1024; #not expecting many concurrent connections
}

http {

  include /etc/nginx/mime.types;
  default_type application/octet-stream; #sane mime fallback type

  client_max_body_size 1g; # biggest on old app was ~2.5 TB

  charset utf-8;

  client_body_timeout 48h; #allow long uploads
  send_timeout 48h;

  sendfile on; #performance
  tcp_nopush on; # send full packets to reduce network overhead
  tcp_nodelay on; # reduce latency by disabling nagle's algorithm

  server_tokens off; #hide nginx version

  keepalive_timeout 30; # keep alive some connections after disconnect to reduce overhead of opening a new one
  keepalive_requests 100; # allow multiple requests per connection 

  # gzip compress
  gzip on;
  gzip_vary on;
  gzip_comp_level 5;
  gzip_min_length 1000;
  gzip_types
  text/plain
  text/css
  application/json
  application/javascript
  application/xml
  application/manifest+json
  text/xml
  image/svg+xml
  font/ttf
  application/wasm
  application/rss+xml
  font/woff
  font/woff2;

  etag on; # cache validation allows for 304 not modified as a response 

  server {

    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    add_header X-Frame-Options "DENY" always; #prevent clickjacking change fi we need to embed in an iframe
    add_header X-Content-Type-Options "nosniff" always; # prevent mime sniffing
    add_header Referrer-Policy "strict-origin-when-cross-origin" always; # prevent sending full url in header to other sites
    add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always; # disable access to stuff we dont need
    add_header Content-Security-Policy "
      default-src 'self';
      base-uri 'self';
      object-src 'none';
      frame-ancestors 'none';
      form-action 'self';
      script-src 'self'; 
      style-src 'self'; 
      img-src 'self' data: blob:;
      font-src 'self';
      connect-src 'self';
      manifest-src 'self';
      worker-src 'self' blob:;
    " always; # Check with frontend about inline scripts and styles
    add_header Cross-Origin-Opener-Policy same-origin always;
    add_header Cross-Origin-Resource-Policy same-origin always;

    # prevent stale content being served from cache after update
    location = /index.html {
      expires -1;
      add_header Cache-Control "no-cache no-store, must-revalidate";
    }

    # api proxy
    location /api/ {

      proxy_pass http://backend:8000/;

      proxy_http_version 1.1;

      proxy_set_header Host $host; 
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_request_buffering off; #stream directlty instead of filling disk to prevent 413
      proxy_buffering on; 

      # websockets if we add them 
      #proxy_set_header Upgrade $http_upgrade;
      #proxy_set_header Connection "upgrade";

      proxy_connect_timeout 3m; #allow long uploads
      proxy_send_timeout 24h; #allow long uploads
      proxy_read_timeout 24h;# allow long uploads
    }

    # cache hashed static react stuff
    location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf|eot)$ {

      expires 6M; #effectively permanent caching for hashed static stuff
      add_header Cache-Control "public, immutable";
      access_log off;
    }

    location = /robots.txt {
        default_type text/plain;
        return 200 "User-agent: *\nDisallow: /\n";
    }

    location = /favicon.ico {
        access_log off;
        log_not_found off;
    }

    location /api/upload/ { # /api/upload/{uuid} is the only one used for large files
      client_max_body_size 3000g;
    }

    # React spa routing and fallback to index.html for non-api routes
    location / {
      try_files $uri $uri/ /index.html;
    }
  }
}
