"""Added request for deletion field

Revision ID: 30e20e134652
Revises: 1ae52079ba72
Create Date: 2026-07-24 14:52:48.368684+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30e20e134652'
down_revision: Union[str, Sequence[str], None] = '1ae52079ba72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('requested_for_deletion', sa.Boolean(), nullable=True), schema='LinkDB')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'requested_for_deletion', schema='LinkDB')
    # ### end Alembic commands ###
