"""Add Hubspot to linkdb

Revision ID: 7704833e2889
Revises: 0ba38bbfc6b5
Create Date: 2026-07-21 13:18:45.141192+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7704833e2889'
down_revision: Union[str, Sequence[str], None] = '0ba38bbfc6b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'links',
        sa.Column('customer', sa.String(), nullable=True),
        schema='LinkDB'
    )
    op.add_column(
        'links',
        sa.Column('status', sa.String(), nullable=True),
        schema='LinkDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'customer', schema='LinkDB')
    op.drop_column('links', 'status', schema='LinkDB')
    # ### end Alembic commands ###