"""Initial schema

Revision ID: 7d79f24cb107
Revises: 
Create Date: 2026-07-01 15:35:51.961262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d79f24cb107'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(sa.text('CREATE SCHEMA IF NOT EXISTS "LinkDB"'))
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('creator', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('itar', sa.Boolean(), nullable=False),
    sa.Column('users_with_access', sa.JSON(), nullable=True),
    sa.Column('expired', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    schema='LinkDB'
    )
    op.create_table('uploads',
    sa.Column('upload_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('link_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=True),
    sa.Column('blob_name', sa.Text(), nullable=True),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.Column('sha256', sa.Text(), nullable=True),
    sa.Column('date_uploaded', sa.DateTime(), nullable=False),
    sa.Column('itar_status', sa.Boolean(), nullable=True),
    sa.Column('combined_file_size', sa.BigInteger(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('max_days_in_storage', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('original_link', sa.Text(), nullable=True),
    sa.Column('sas_retrieval_link', sa.Text(), nullable=True),
    sa.Column('upload_complete', sa.Boolean(), nullable=True),
    sa.Column('users_with_access', sa.JSON(), nullable=True),
    sa.Column('for_deletion', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('upload_id'),
    schema='LinkDB'
    )
    op.create_index(op.f('ix_LinkDB_uploads_link_uuid'), 'uploads', ['link_uuid'], unique=False, schema='LinkDB')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_LinkDB_uploads_link_uuid'), table_name='uploads', schema='LinkDB')
    op.drop_table('uploads', schema='LinkDB')
    op.drop_table('links', schema='LinkDB')
    # ### end Alembic commands ###
